#=================================================================
# Initialization of the background colors and theme of the website
#==================================================================

#Source: ChatGPT for the creation of the folder config.toml  

[theme]
backgroundColor="#faf9f9"

secondaryBackgroundColor="#d3dbd1"

primaryColor="#0d4200"

textColor="#22313f"

font ="serif"
